import type { Lang } from "./language";

export const UI = {
  es: {
    dashboard: "Dashboard",
    loadingProgress: "Cargando progreso…",
    level: "Nivel",
    xp: "XP",
    streakDays: "Racha (días)",
    dueToday: "Repaso hoy",
    overallProgress: "Progreso general",
    conceptsMastered: (m: number, t: number) => `${m}/${t} conceptos dominados`,
    phases: "Fases",
    phaseLabel: (order: number, title: string) => `Fase ${order} — ${title}`,
    viewPhase: "Ver fase",
    flashcardsLink: "Tarjetas",
    quizLink: "Quiz",
    phaseNotFound: "Fase no encontrada.",
    goToFlashcards: "Ir a las tarjetas →",
    goToQuiz: "Ir al quiz →",
    synthesisTitle: "🧩 Cómo funciona todo mezclado (síntesis de la fase)",
    statusNotStarted: "sin empezar",
    statusLearning: "en progreso",
    statusMastered: "dominado",
    conceptAndExample: "📖 Concepto + ejemplo",
    example: "Ejemplo",
    relationTitle: "🔗 Cómo se relaciona con otros conceptos",
    characterTitle: (franchise: string) => `🎭 Asociación personaje-acción (${franchise})`,
    quizLabel: "Quiz",
    readyForQuiz: "Ya la leí — quiero el quiz",
    next: "Siguiente",
    quizComplete: "Quiz completo 🎉",
    flashcardsComplete: "Tarjetas completas 🎉",
    xpEarned: (xp: number) => `Ganaste ${xp} XP en esta ronda.`,
    backToDashboard: "Volver al dashboard",
    correctMastered: (xp: number) => `¡Correcto! Concepto dominado. +${xp} XP`,
    correctPlain: (xp: number) => `¡Correcto! +${xp} XP`,
    incorrect: (answer: string) => `No era esa — la respuesta correcta era: "${answer}"`,
    showAnswer: "Mostrar respuesta",
    recallHint: "Intentá recitar la respuesta de memoria antes de voltear la tarjeta.",
    howWellRemembered: "¿Qué tan bien la recordaste?",
    gradeAgain: "Otra vez",
    gradeHard: "Difícil",
    gradeGood: "Bien",
    gradeEasy: "Fácil",
    gradedMastered: (xp: number) => `Concepto dominado. +${xp} XP`,
    gradedPlain: (xp: number) => `+${xp} XP`,
    gradedNone: "Sin XP esta vez — va a repetirse pronto",
    speakTooltip: "Escuchar pronunciación en inglés",
    flashcardsSubtitle: "Tarjetas",
    skip: "Saltar",
    guide: "Guía",
    recitationNav: "Guion",
    recitationTitle: "Guion de recitación",
    recitationIntro:
      "Los 96 conceptos en el mismo orden de la cadena de personajes (fase 0 → fase 8). Por cada uno, primero intentá recitar de memoria la lección y el ejemplo usando solo el título y la escena del personaje como pista; recién después leé el resto para corregirte.",
    recitationHint: "Pista",
    recitationRelation: "Relación",
    recitationQuestion: "Pregunta de autoevaluación",
  },
  en: {
    dashboard: "Dashboard",
    loadingProgress: "Loading progress…",
    level: "Level",
    xp: "XP",
    streakDays: "Streak (days)",
    dueToday: "Due today",
    overallProgress: "Overall progress",
    conceptsMastered: (m: number, t: number) => `${m}/${t} concepts mastered`,
    phases: "Phases",
    phaseLabel: (order: number, title: string) => `Phase ${order} — ${title}`,
    viewPhase: "View phase",
    flashcardsLink: "Flashcards",
    quizLink: "Quiz",
    phaseNotFound: "Phase not found.",
    goToFlashcards: "Go to flashcards →",
    goToQuiz: "Go to quiz →",
    synthesisTitle: "🧩 How it all fits together (phase synthesis)",
    statusNotStarted: "not started",
    statusLearning: "in progress",
    statusMastered: "mastered",
    conceptAndExample: "📖 Concept + example",
    example: "Example",
    relationTitle: "🔗 How this relates to other concepts",
    characterTitle: (franchise: string) => `🎭 Character-action association (${franchise})`,
    quizLabel: "Quiz",
    readyForQuiz: "I've read it — quiz me",
    next: "Next",
    quizComplete: "Quiz complete 🎉",
    flashcardsComplete: "Flashcards complete 🎉",
    xpEarned: (xp: number) => `You earned ${xp} XP this round.`,
    backToDashboard: "Back to dashboard",
    correctMastered: (xp: number) => `Correct! Concept mastered. +${xp} XP`,
    correctPlain: (xp: number) => `Correct! +${xp} XP`,
    incorrect: (answer: string) => `Not quite — the correct answer was: "${answer}"`,
    showAnswer: "Show answer",
    recallHint: "Try to recite the answer from memory before flipping the card.",
    howWellRemembered: "How well did you remember it?",
    gradeAgain: "Again",
    gradeHard: "Hard",
    gradeGood: "Good",
    gradeEasy: "Easy",
    gradedMastered: (xp: number) => `Concept mastered. +${xp} XP`,
    gradedPlain: (xp: number) => `+${xp} XP`,
    gradedNone: "No XP this time — it'll come back around soon",
    speakTooltip: "Listen to English pronunciation",
    flashcardsSubtitle: "Flashcards",
    skip: "Skip",
    guide: "Guide",
    recitationNav: "Script",
    recitationTitle: "Recitation script",
    recitationIntro:
      "All 96 concepts in the same order as the character chain (phase 0 → phase 8). For each one, first try to recite the lesson and example from memory using only the title and the character scene as a cue; only then read the rest to correct yourself.",
    recitationHint: "Cue",
    recitationRelation: "Relation",
    recitationQuestion: "Self-check question",
  },
} satisfies Record<Lang, Record<string, unknown>>;

export function uiFor(lang: Lang) {
  return UI[lang];
}
